### ISSUE TITLE
Allow navigating to contact type page

### ISSUE THREAD

**Issue by sondreb** [block-core/blockcore-explorer#44]
It should be possible to click the "Contract Type" on a smart contract transaction details and see all unique types of that contract.

![image](https://user-images.githubusercontent.com/309938/156876671-dc9850d7-f466-4a6e-968f-bbc83b588745.png)

**Comment by dangershony** [comment]
You mean a list of all addresses of the contracts of that type?
Should be pretty easy to do

**Comment by sondreb** [comment]
I presume there are multiple types of NFT contracts? The idea was to show a unique view of all deployed NFT contracts, and when you pick one of those, then you get yet another view.
