### ISSUE TITLE
Enable selection of backend Indexers 

### ISSUE THREAD

**Issue by dangershony** [block-core/blockcore-explorer#57]
My plan: 
1. On the API page of the explorer change the API link to be a text box to enable users to change the indexer endpoint.  
2. And fetch a list of Indexers from the DNS servers configured in the chaininfo repo and let th user the option to pick one.  
3. When an exception happens with an indexer connection display an error message to notify a user they can change the default indexer.  
4. (Optional) store a saved indexer in local storage so in the future it will be used again (also for privacy so a user that changes to use their own indexer will keep that configuration)

**Comment by sondreb** [comment]
Saving it in local storage is a good idea, and the explorer is already installable as an PWA: 
![image](https://user-images.githubusercontent.com/309938/174893157-b8f048ef-1616-4c71-8701-8479d0e66573.png)

**Comment by sondreb** [comment]
This is completed, and recently was updated to use the new library: https://www.npmjs.com/package/@blockcore/dns
